from fastapi import APIRouter, Depends, Form
from sqlalchemy.orm import Session
from database import get_db
from schemas import ReportResponse
from models.report_model import Report
import os
import uuid
from datetime import datetime

router = APIRouter()

@router.get("/", response_model=list[ReportResponse])
def get_reports(db: Session = Depends(get_db)):
    return db.query(Report).order_by(Report.created_at.desc()).all()

@router.post("/generate", response_model=ReportResponse)
def generate_report(
    standard_id: int = Form(...),
    generated_by: int = Form(...),
    db: Session = Depends(get_db)
):
    # Generate a simple text report
    unique_filename = f"report_{standard_id}_{uuid.uuid4().hex[:8]}.txt"
    
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    REPORTS_DIR = os.path.join(BASE_DIR, "uploads", "reports")
    os.makedirs(REPORTS_DIR, exist_ok=True)
    file_path = os.path.join(REPORTS_DIR, unique_filename)
    
    report_content = f"Compliance Report\n=================\nGenerated at: {datetime.now().isoformat()}\nStandard ID: {standard_id}\nGenerated By: User {generated_by}\n\nSummary:\nThis is an automated compliance report. All controls have been reviewed."
    
    with open(file_path, "w") as f:
        f.write(report_content)
        
    serve_path = f"/uploads/reports/{unique_filename}"
    
    new_report = Report(
        standard_id=standard_id,
        generated_by=generated_by,
        summary=f"Automated report for standard {standard_id}",
        file_path=serve_path
    )
    db.add(new_report)
    db.commit()
    db.refresh(new_report)
    return new_report
